### ISSUE TITLE
Example URL

### ISSUE THREAD

**Issue by FranklinYu** [glombek/ShortlinkExtension#2]
Is there any example URL where I can try out this extension?

**Comment by glombek** [comment]
Most Wordpress sites will have a wp.me official shortlink.

Here's an example: https://www.wpbeginner.com/beginners-guide/how-to-create-your-own-customized-short-url-for-your-blog/

The plugin shows http://wpbeg.in/e5qcqp as the shortlink

**Comment by FranklinYu** [comment]
Thanks. Is this extension intended for personal use? In other words, would contribution be welcome? The example isn’t mentioned in ReadMe nor the description on Chrome Web Store (that’s why I asked in the first place); the content script almost seems like minified one-liner.

**Comment by glombek** [comment]
Hi Franklin,

This was originally created as a tool for my own use, but I acknowledge there's not much similar in the Web Store, only extensions that _create_ shortlinks rather than finding ones generated by the site.

You're right, the description is lacking some love, and needs updating to match how Chrome now shows these kind of extensions.

I'd absolutely welcome any assistance you want to provide, and will happily review any pull requests.

Let's re-inject some life into this and get this extension usable!

Joe
